steps:
  - name: gradle:7.4.1-jdk11
    entrypoint: gradle
    args: ['assemble']

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - HelloWorld
      - --region=us-central1
      - --source=.
      - --trigger-http
      - --runtime=java11
      - --entry-point=functions.HelloWorld
