# HTTP function "HelloWorld"
steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['build']
  dir: '/'
- name: 'gcr.io/cloud-builders/gcloud'
  # omit --entry-point because the function provide a entrypoint named same as function name.
  args: ['functions', 'deploy', 'HelloWorld', '--trigger-http', '--runtime', 'java11']
  dir: '/'
